name: user-statistician

on:
  schedule:
    - cron: '* */6 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/multiple-stats-cards.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the languages distribution
      uses: cicirello/user-statistician@v1
      with:
        image-file: assets/languages.svg
        colors: dark
        hide-keys: general, contributions, repositories
        commit-and-push: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate the contributions stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: assets/contribs.svg
        colors: dark
        hide-keys: general, languages, repositories
        commit-and-push: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate the repositories stats
      uses: cicirello/user-statistician@v1
      with:
        image-file: assets/repos.svg
        colors: dark
        hide-keys: general, contributions, languages
        commit-and-push: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update GitHub statistics"
        add: "assets/*.svg"
